export const websocketActionTypes = {
  WEBSOCKET_CONNECTION_START: "WEBSOCKET_CONNECTION_START",
  WEBSOCKET_CONNECTION_SUCCESS: "WEBSOCKET_CONNECTION_SUCCESS",
  WEBSOCKET_CONNECTION_FAILURE: "WEBSOCKET_CONNECTION_FAILURE",
  WEBSOCKET_CONNECTION_DISCONNECT: "WEBSOCKET_CONNECTION_DISCONNECT",
  WEBSOCKET_CONNECTION_RECONNECT: "WEBSOCKET_CONNECTION_RECONNECT",
  WEBSOCKET_CONNECTION_CLOSE: "WEBSOCKET_CONNECTION_CLOSE",
  WEBSOCKET_SUB_START: "WEBSOCKET_SUB_START",
  WEBSOCKET_SUB_SUCCESS: "WEBSOCKET_SUB_SUCCESS",
  WEBSOCKET_SUB_FAILURE: "WEBSOCKET_SUB_FAILURE",
  WEBSOCKET_UNSUB_START: "WEBSOCKET_UNSUB_START",
  WEBSOCKET_UNSUB_SUCCESS: "WEBSOCKET_UNSUB_SUCCESS",
  WEBSOCKET_UNSUB_FAILURE: "WEBSOCKET_UNSUB_FAILURE",

};
