export const portfolioActionTypes = {
  PORTFOLIO_FETCH_START: "PORTFOLIO_FETCH_START",
  PORTFOLIO_FETCH_SUCCESS: "PORTFOLIO_FETCH_SUCCESS",
  PORTFOLIO_FETCH_FAILURE: "PORTFOLIO_FETCH_FAILURE",
  PORTFOLIO_STOCK_TRANSACTION_START: "PORTFOLIO_STOCK_TRANSACTION_START",
  PORTFOLIO_STOCK_TRANSACTION_SUCCESS: "PORTFOLIO_STOCK_TRANSACTION_SUCCESS",
  PORTFOLIO_STOCK_TRANSACTION_FAILURE: "PORTFOLIO_STOCK_TRANSACTION_FAILURE",
  PORTFOLIO_STOCK_TRANSACTION_UPDATE_START:
    "PORTFOLIO_STOCK_TRANSACTION_UPDATE_START",
  PORTFOLIO_STOCK_TRANSACTION_UPDATE_SUCCESS:
    "PORTFOLIO_STOCK_TRANSACTION_UPDATE_SUCCESS",
  PORTFOLIO_STOCK_TRANSACTION_UPDATE_FAILURE:
    "PORTFOLIO_STOCK_TRANSACTION_UPDATE_FAILURE",
  PORTFOLIO_STOCK_TRANSACTION_DELETE_START:
    "PORTFOLIO_STOCK_TRANSACTION_DELETE_START",
  PORTFOLIO_STOCK_TRANSACTION_DELETE_SUCCESS:
    "PORTFOLIO_STOCK_TRANSACTION_DELETE_SUCCESS",
  PORTFOLIO_STOCK_TRANSACTION_DELETE_FAILURE:
    "PORTFOLIO_STOCK_TRANSACTION_DELETE_FAILURE",
  PORTFOLIO_STOCK_DELETE_START: "PORTFOLIO_STOCK_DELETE_START",
  PORTFOLIO_STOCK_DELETE_SUCCESS: "PORTFOLIO_STOCK_DELETE_SUCCESS",
  PORTFOLIO_STOCK_DELETE_FAILURE: "PORTFOLIO_STOCK_DELETE_FAILURE",
  FETCH_TRANSACTION_START: "FETCH_TRANSACTION_START",
  FETCH_TRANSACTION_SUCCESS: "FETCH_TRANSACTION_SUCCESS",
  FETCH_TRANSACTION_FAILURE: "FETCH_TRANSACTION_FAILURE",
  FETCH_NEWS_START: "FETCH_NEWS_START",
  FETCH_NEWS_SUCCESS: "FETCH_NEWS_SUCCESS",
  FETCH_NEWS_FAILURE: "FETCH_NEWS_FAILURE",
};
