# Generated by Django 3.0.13 on 2021-04-22 12:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20210421_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockpricedata',
            name='price_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
