# Generated by Django 3.0.13 on 2021-04-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20210422_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockpricedata',
            name='price_data',
        ),
        migrations.AddField(
            model_name='stockpricedata',
            name='close_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stockpricedata',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockpricedata',
            name='high',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stockpricedata',
            name='low',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stockpricedata',
            name='open_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stockpricedata',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
