# Generated by Django 3.0.13 on 2021-04-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20210422_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpricedata',
            name='adj_close',
            field=models.FloatField(default=0),
        ),
    ]
